debian/scripts/xen-toolstack-wrapper: Show selected toolstack in error message.
git-svn-id: svn://anonscm.debian.org/svn/pkg-xen/trunk@937 19d14552-db0c-0410-aa19-817c7d738a49

diff --git a/xen-common/debian/scripts/xen-toolstack-wrapper b/xen-common/debian/scripts/xen-toolstack-wrapper
--- a/xen-common/debian/scripts/xen-toolstack-wrapper
+++ b/xen-common/debian/scripts/xen-toolstack-wrapper
@@ -4,7 +4,7 @@ COMMAND="$(basename $0)"
 TOOLSTACK=$(. /usr/lib/xen-common/bin/xen-toolstack); RET=$?; [ $RET -eq 0 ] || exit $RET
 
 if [ "$(basename "$TOOLSTACK")" != "$COMMAND" ]; then
-    echo "ERROR:  A different toolstack have been selected!" >&2
+    echo "ERROR:  A different toolstack ($(basename "$TOOLSTACK")) have been selected!" >&2
     exit 1
 fi
 
