debian/scripts/xen-dir, debian/scripts/xen-version: Always write error messages.
git-svn-id: svn://anonscm.debian.org/svn/pkg-xen/trunk@943 19d14552-db0c-0410-aa19-817c7d738a49

diff --git a/xen-common/debian/scripts/xen-version b/xen-common/debian/scripts/xen-version
--- a/xen-common/debian/scripts/xen-version
+++ b/xen-common/debian/scripts/xen-version
@@ -1,17 +1,7 @@
 #!/bin/sh -e
 
-while getopts "v" OPT; do
-    case "$OPT" in
-	v)
-	VERBOSE=1
-	;;
-    esac
-done
-
 error() {
-    if [ "$VERBOSE" ]; then
-        echo "ERROR: " "$@" >&2
-    fi
+    echo "ERROR: " "$@" >&2
     exit 1
 }
 
