* debian/changelog: Update. * debian/xen-utils-common.xend.init,   debian/xen-utils-common.xendomains.init:   Call xen-utils-version without parameters. * scripts/xen-utils-version: Only detect version. * scripts/xen-utils-wrapper: Move directory detection.
git-svn-id: svn://anonscm.debian.org/svn/pkg-xen/trunk@686 19d14552-db0c-0410-aa19-817c7d738a49

diff --git a/xen-common/scripts/xen-utils-version b/xen-common/scripts/xen-utils-version
--- a/xen-common/scripts/xen-utils-version
+++ b/xen-common/scripts/xen-utils-version
@@ -1,48 +1,28 @@
 #!/bin/bash
 
-while getopts "qv:" OPT; do
+while getopts "v" OPT; do
     case "$OPT" in
-	q)
-	QUIET=1
-	;;
 	v)
-	VERSION="$OPTARG"
+	VERBOSE=1
 	;;
     esac
 done
 
-if [ -z "$VERSION" ]; then
-    if [ -e "/sys/hypervisor/type" ]; then
-        if [ "$(cat /sys/hypervisor/type)" = xen ]; then
-            DIR=/sys/hypervisor/version
-            VERSION_EXTRA=$(cat $DIR/extra)
-            if [ "$VERSION_EXTRA" = "-unstable" ]; then
-                VERSION=unstable
-            else
-                VERSION="$(cat $DIR/major).$(cat $DIR/minor)$VERSION_EXTRA"
-            fi
+if [ -e "/sys/hypervisor/type" ]; then
+    if [ "$(cat /sys/hypervisor/type)" = xen ]; then
+        DIR=/sys/hypervisor/version
+        VERSION_EXTRA=$(cat $DIR/extra)
+        if [ "$VERSION_EXTRA" = "-unstable" ]; then
+            VERSION=unstable
         else
-            [ "$QUIET" ] || echo "WARING!  Can't read type from sysfs!" >&2
+            VERSION="$(cat $DIR/major).$(cat $DIR/minor)$VERSION_EXTRA"
         fi
     else
-        [ "$QUIET" ] || echo "WARING!  Can't find hypervisor information in sysfs!" >&2
+        [ "$VERBOSE" ] && echo "WARING!  Can't read type from sysfs!" >&2
     fi
+else
+    [ "$VERBOSE" ] && echo "WARING!  Can't find hypervisor information in sysfs!" >&2
 fi
 
-if [ -z "$VERSION" ]; then
-    VERSION="default"
-fi
-
-if [ -d "/usr/lib/xen-$VERSION" ]; then
-    echo "$VERSION"
-    exit 0
-fi
-
-if [ -d "/usr/lib/xen-default" ]; then
-    [ "$QUIET" ] || echo "WARING!  Can't find version $VERSION of xen utils, fallback to default version!" >&2
-    echo "default"
-    exit 0
-fi
-
-[ "$QUIET" ] || echo "ERROR!  Can't find default version of xen utils, bailing out!" >&2
-exit 1
+echo "$VERSION"
+exit 0
diff --git a/xen-common/scripts/xen-utils-wrapper b/xen-common/scripts/xen-utils-wrapper
--- a/xen-common/scripts/xen-utils-wrapper
+++ b/xen-common/scripts/xen-utils-wrapper
@@ -1,7 +1,22 @@
 #!/bin/bash
 
-libdir=/usr/lib
-command="$(basename $0)"
-version=$($libdir/xen-common/bin/xen-utils-version -v "$XEN_VERSION")
-[ "$version" ] && exec "$libdir/xen-$version/bin/$command" "$@"
-exit 127
+set -e
+
+COMMAND="$(basename $0)"
+VERSION=$(/usr/lib/xen-common/bin/xen-utils-version -v)
+
+if [ -z "$VERSION" ]; then
+    VERSION="default"
+fi
+
+if [ -d "/usr/lib/xen-$VERSION" ]; then
+    DIR="/usr/lib/xen-$VERSION"
+elif [ -d "/usr/lib/xen-default" ]; then
+    echo "WARING!  Can't find version $VERSION of xen utils, fallback to default version!" >&2
+    DIR="/usr/lib/xen-default"
+else
+    echo "ERROR!  Can't find default version of xen utils, bailing out!" >&2
+    exit 127
+fi
+
+exec "$libdir/xen-$version/bin/$command" "$@"
