scripts/xen-utils-root: Collect version from /sys/hypervisor.
git-svn-id: svn://anonscm.debian.org/svn/pkg-xen/trunk@276 19d14552-db0c-0410-aa19-817c7d738a49

diff --git a/xen-common/scripts/xen-utils-root b/xen-common/scripts/xen-utils-root
--- a/xen-common/scripts/xen-utils-root
+++ b/xen-common/scripts/xen-utils-root
@@ -11,7 +11,18 @@ while getopts "qv:" OPT; do
     esac
 done
 
-# TODO: real version detection
+if [ -z "$VERSION" ]; then
+    if [ -d "/sys/hypervisor" ]; then
+        if [ "$(cat /sys/hypervisor/type)" = xen ]; then
+            dir=/sys/hypervisor/version/
+            VERSION="$(cat $dir/major).$(cat $dir/minor)$(cat $dir/extra)"
+        else
+            [ "$QUIET" ] || echo "WARING!  Can't read type from sysfs!" >&2
+        fi
+    else
+        [ "$QUIET" ] || echo "WARING!  Can't find hypervisor information in sysfs!" >&2
+    fi
+fi
 
 if [ -z "$VERSION" ]; then
     VERSION="default"
@@ -32,4 +43,3 @@ fi
 
 [ "$QUIET" ] || echo "ERROR!  Can't find default version of xen utils, bailing out!" >&2
 exit 1
-
